### ISSUE TITLE
peer-to-peer code review Feedback

### ISSUE THREAD

**Issue by thecodechaser** [AnselemOdims/Portfolio#14]
Suggestions, improvements, feedback

**Comment by RayhanTabase** [comment]
Everything looks great, keep up the good work.👏👏👏

**Comment by thecodechaser** [comment]
Hello, @AnselemOdims 👋

You did great so far, Your project is already looking great, You probably did hard work for this 👍.

To highlight😄.
-Project directory is clean 
-Clean code
-Descriptive Readme file

Great job 👍

**Comment by AnselemOdims** [comment]
Thank you guys so much for the kind words.
